(()=>{'use strict';
const $=s=>document.querySelector(s);
const PROCESSOR_URL=$('#processorUrl').textContent.trim();
const RAW='https://raw.githubusercontent.com/anuchit1tube168-cmd/RTAFNC-/main/agis-agent-armada-os/apps-script/AGIS_Processor_v2_Code.gs';
const state={health:null,checks:{}};
function log(value){$('#log').textContent=typeof value==='string'?value:JSON.stringify(value,null,2)}
function badge(ok,text){const el=$('#healthBadge');el.textContent=text;el.className='badge '+(ok?'ok':'bad')}
function render(){const h=state.health||{},actions=h.actions||[];const checks=[['Processor ตอบกลับ',Boolean(h.ok)],['Version 2.0.0',h.version==='2.0.0'],['output.save',actions.includes('output.save')],['output.list',actions.includes('output.list')],['chat.append',actions.includes('chat.append')],['chat.list',actions.includes('chat.list')],['Spreadsheet ID ถูกต้อง',h.spreadsheetId===$('#sheetId').textContent.trim()],['Output Folder ถูกต้อง',h.outputFolderId===$('#folderId').textContent.trim()]];state.checks=Object.fromEntries(checks);$('#checklist').innerHTML=checks.map(([text,ok])=>`<div class="check ${ok?'ok':''}"><i>${ok?'✓':'!'}</i><span>${text}</span></div>`).join('');const pass=checks.every(x=>x[1]);badge(pass,pass?'PROCESSOR v2 READY':h.ok?`VERSION ${h.version||'UNKNOWN'}`:'OFFLINE / v1');return pass}
async function health(){badge(false,'กำลังตรวจ...');try{const response=await fetch(PROCESSOR_URL+'?ts='+Date.now(),{cache:'no-store'});const data=await response.json();state.health=data;log(data);const pass=render();return{ok:pass,data}}catch(error){state.health={ok:false,error:error.message};render();log(state.health);return{ok:false,error:error.message}}}
async function copy(id){const text=$('#'+id).textContent.trim();await navigator.clipboard.writeText(text);badge(true,'COPIED')}
async function copyCode(){const button=$('#copyCode');button.disabled=true;button.textContent='กำลังโหลดโค้ด...';try{const response=await fetch(RAW,{cache:'no-store'});if(!response.ok)throw new Error('โหลด Code.gs ไม่สำเร็จ');const text=await response.text();await navigator.clipboard.writeText(text);button.textContent='Copied Code.gs v2 ✓';log(`คัดลอก Code.gs v2 แล้ว\nจำนวน ${text.length.toLocaleString()} ตัวอักษร\nนำไปวางแทน Code.gs เดิมได้เลย`)}catch(error){log({ok:false,error:error.message,rawUrl:RAW});button.textContent='เปิดไฟล์ใน GitHub แล้ว Copy'}finally{setTimeout(()=>{button.disabled=false;button.textContent='Copy Code.gs v2'},3500)}}
function downloadReceipt(report,token){const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=window.URL.createObjectURL(blob);link.download=`AGIS-Processor-v2-Smoke-${token}.json`;document.body.appendChild(link);link.click();setTimeout(()=>{window.URL.revokeObjectURL(link.href);link.remove()},600)}
async function smoke(){const button=$('#runSmoke');button.disabled=true;button.textContent='กำลังทดสอบ...';const report={system:'AGIS Processor v2 Smoke Test',testedAt:new Date().toISOString(),url:PROCESSOR_URL,steps:[]};let token=Date.now();try{const healthResult=await health();report.steps.push({step:'health',ok:healthResult.ok,result:healthResult.data||healthResult.error});if(!healthResult.ok)throw new Error('Processor ยังไม่ใช่ v2.0.0');const setup=await AGISSProcessor.call('setup');report.steps.push({step:'setup',ok:Boolean(setup.ok),result:setup});if(!setup.ok)throw new Error('setup failed');token=Date.now();const jobId='SYSTEM-SMOKE-V2',missionId='SMOKE-'+token;const output=await AGISSProcessor.call('output.save',{jobId,missionId,status:'draft',final:false,files:[{fileName:`processor-v2-smoke-${token}.txt`,mimeType:'text/plain',content:`AGIS Processor v2 smoke test\n${new Date().toISOString()}\nPASS when this file exists in Google Drive.`}]});report.steps.push({step:'output.save',ok:Boolean(output.ok),result:output});const chat=await AGISSProcessor.call('chat.append',{jobId,missionId,author:'Doctor',target:'ALL',message:`Processor v2 smoke test ${token}`,type:'system'});report.steps.push({step:'chat.append',ok:Boolean(chat.ok),result:chat});const outputs=await AGISSProcessor.call('output.list',{jobId,limit:10});report.steps.push({step:'output.list',ok:Boolean(outputs.ok&&outputs.outputs?.length),result:outputs});const chats=await AGISSProcessor.call('chat.list',{jobId,limit:10});report.steps.push({step:'chat.list',ok:Boolean(chats.ok&&chats.chat?.length),result:chats});report.ok=report.steps.every(x=>x.ok);report.result=report.ok?'PASS':'FAIL';log(report);badge(report.ok,report.ok?'FULL SMOKE PASS':'SMOKE FAIL');downloadReceipt(report,token)}catch(error){report.ok=false;report.result='FAIL';report.error=error.message;log(report);badge(false,'SMOKE FAIL')}finally{button.disabled=false;button.textContent='Run Full Smoke Test'}}
document.addEventListener('click',event=>{const button=event.target.closest('[data-copy]');if(button)copy(button.dataset.copy)});
$('#copyCode').onclick=copyCode;
$('#checkHealth').onclick=health;
$('#runSmoke').onclick=smoke;
health();
})();