(()=>{'use strict';
const F=window.ProjectForge,U=window.ProjectForgeUI,{D,$,$$,esc,canon,S,save,toast,addChat,api,slug,download}=F;
async function syncCaptain(){if(!S.project.name||!S.project.goal){toast('กรอกชื่อโครงการและ One Piece ก่อน');$('#projectName').focus();return}addChat('AGIS',`รับโครงการ ${S.project.name} เพื่อเริ่ม Loop`);const c=await api('job.create',()=>AGISSProcessor.call('job.create',{bossCommand:`สร้างและอัปเกรดโครงการ ${S.project.name}`,onePiece:S.project.goal,priority:S.project.priority,jobType:S.project.type,ownerAgent:'AGIS'}));if(!c.ok){toast('Processor ไม่พร้อม — เก็บโครงการไว้ในเครื่องแล้ว');return}S.jobId=c.jobId;const r=await api('job.route',()=>AGISSProcessor.call('job.route',{jobId:S.jobId}));if(r.ok){S.missions=r.missions||[];S.stage=Math.max(S.stage,5);S.quests=S.missions.map((m,i)=>({id:m.missionId||`Q${i+1}`,title:m.title||'Mission',owner:canon(m.ownerAgent),status:m.status||'Todo',xp:Number(m.xpReward)||75,evidence:m.evidenceUrl||''}));addChat('Navigator',`แตกงานเป็น ${S.missions.length} Mission แล้ว`);save();U.renderAll();toast('ส่งเข้า Captain และ Route Mission สำเร็จ')}}
function generateQuests(){S.quests=F.defaultQuests.map(q=>({id:q[0],title:q[1],owner:q[2],status:q[3],xp:q[4],evidence:''}));S.stage=Math.max(S.stage,5);addChat('Navigator','สร้าง Quest Backlog 9 ภารกิจแล้ว');save();U.renderAll();toast('สร้าง Quest สำเร็จ')}
function nextQuestStatus(id){const q=S.quests.find(x=>x.id===id);if(!q)return;const order=['Todo','Working','Review','Done'];if(q.status==='Review'&&!q.evidence){const url=prompt('Evidence URL ก่อน Done');if(!url)return;q.evidence=url}q.status=order[(order.indexOf(q.status)+1)%order.length];if(q.status==='Done'){S.xp+=q.xp;addChat(q.owner,`${q.title} เสร็จแล้ว +${q.xp} XP`)}save();U.renderAll()}
function addAsset(){const name=$('#assetName').value.trim();if(!name)return;S.assets.push({name,type:$('#assetType').value,status:$('#assetStatus').value,url:$('#assetUrl').value.trim(),createdAt:new Date().toISOString()});$('#assetDialog').close();save();U.renderAll();toast('เพิ่ม Asset แล้ว')}
function claimReward(){const earned=S.quests.filter(q=>q.status==='Done').reduce((n,q)=>n+q.xp,0),bonus=S.receipt?200:0;S.xp=Math.max(S.xp,earned+bonus);addChat('Clone',`คำนวณ Idle Rewards แล้ว: ${S.xp} XP`);save();U.renderAll();toast(`Fleet XP ${S.xp}`)}
function upgrade(){S.forgeLevel++;S.xp+=100;const v=S.project.version.split('.').map(Number);v[1]=(v[1]||0)+1;S.project.version=v.join('.');addChat('Fable',`Forge Upgrade เป็น Level ${S.forgeLevel} / v${S.project.version}`);save();U.renderAll();toast('Upgrade สำเร็จ')}
function patch(){const note=prompt('สรุปสิ่งที่เปลี่ยนใน Patch นี้','ปรับ Workflow, Asset และ Production Gate');if(!note)return;S.patches.push({version:S.project.version,date:new Date().toISOString().slice(0,10),note});save();U.renderAll();toast('สร้าง Patch Note แล้ว')}
function bossChallenge(){S.boss=true;S.project.priority='Critical';addChat('Swordsman','เปิด Boss Challenge: ต้องผ่าน Guard, QA, Evidence และ Receipt');save();U.renderAll();toast('Boss Challenge เริ่มแล้ว')}
async function createReceipt(){const ev=S.assets.find(a=>a.url)?.url||S.quests.find(q=>q.evidence)?.evidence;if(!ev){toast('ต้องมี Evidence URL ก่อนสร้าง Receipt');return}const d=await api('receipt.create',()=>AGISSProcessor.call('receipt.create',{jobId:S.jobId,missionId:S.missions?.at(-1)?.missionId||S.quests.at(-1)?.id,evidence:ev,testResult:'Pass',summaryTH:`Project Forge ${S.project.name} ผ่าน Production Gate`,decision:'AGIS Review'}));if(d.ok){S.receipt=d.receipt||d;addChat('Clone','สร้าง Receipt และ Backup แล้ว');save();U.renderAll();toast('Receipt สำเร็จ')}}
async function exportZip(){const p=F.payload();if(window.JSZip){const z=new JSZip();z.file('PROJECT.json',JSON.stringify(p,null,2));z.file('GDD.md',F.markdown());z.file('index.html',F.html());z.file('README.txt','AGIS Project Forge v6\nOpen index.html or GDD.md.');download(`${slug(p.name)}-project.zip`,await z.generateAsync({type:'blob'}),'application/zip')}else download(`${slug(p.name)}-project.json`,JSON.stringify(p,null,2),'application/json')}
async function saveDrive(){const p=F.payload(),d=await api('output.save',()=>AGISSProcessor.call('output.save',{jobId:S.jobId,fileName:`${slug(S.project.name)}-project.json`,mimeType:'application/json',content:JSON.stringify(p)}));if(d.ok&&d.fileUrl){window.open(d.fileUrl,'_blank');toast('บันทึกเข้า Google Drive แล้ว')}else{download(`${slug(S.project.name)}-project.json`,JSON.stringify(p,null,2),'application/json');window.open('https://drive.google.com/drive/my-drive','_blank');toast('เตรียมไฟล์และเปิด Drive แล้ว — Processor v2 จะบันทึกอัตโนมัติ')}}
function bind(){
 $('#projectForm').addEventListener('submit',e=>{e.preventDefault();S.project={name:$('#projectName').value.trim(),goal:$('#projectGoal').value.trim(),type:$('#projectType').value,priority:$('#projectPriority').value,engine:$('#projectEngine').value,platform:$('#projectPlatform').value,version:S.project.version||'0.1.0'};S.stage=Math.max(S.stage,1);addChat('AGIS',`บันทึก Project Profile: ${S.project.name}`);save();U.renderAll();toast('บันทึก Project Profile แล้ว')});
 $('#projectType').addEventListener('change',e=>{S.project.type=e.target.value;const map={'Game Prototype':'Unity 6 / C#','WebApp':'HTML/CSS/JS + PWA','Data Dashboard':'Google Apps Script','AI Agent System':'Google Apps Script','Document / SOP':'Google Apps Script','Research':'Python Tooling'};$('#projectEngine').value=map[e.target.value]||$('#projectEngine').value;U.renderStack()});
 $('#syncCaptainBtn').onclick=$('#runAutoLoop').onclick=syncCaptain;$('#generateQuests').onclick=generateQuests;$('#claimReward').onclick=claimReward;$('#upgradeForge').onclick=upgrade;$('#createPatch').onclick=patch;$('#startBossChallenge').onclick=bossChallenge;$('#addAssetBtn').onclick=()=>$('#assetDialog').showModal();$('#saveAsset').onclick=addAsset;$('#openGuild').onclick=()=>$('#guildInput').focus();
 $('#openCrewLoadout').onclick=()=>{$('#crewLoadout').innerHTML=D.crew.map((c,i)=>`<label class="loadout-item"><span class="avatar" style="--i:${i}"></span><span><b>${esc(c.name)}</b><small>${esc(c.role)}</small></span><input type="checkbox" value="${esc(c.name)}" ${S.crew.includes(c.name)?'checked':''}></label>`).join('');$('#crewDialog').showModal()};
 $('#saveCrewLoadout').onclick=()=>{S.crew=$$('#crewLoadout input:checked').map(x=>x.value);$('#crewDialog').close();save();U.renderAll();toast('บันทึก Crew Loadout แล้ว')};
 $('#guildForm').addEventListener('submit',e=>{e.preventDefault();const i=$('#guildInput');if(!i.value.trim())return;addChat('Boss',`ถึง ${$('#guildTarget').value}: ${i.value.trim()}`,'boss');i.value=''});
 $('#questList').addEventListener('click',e=>{const b=e.target.closest('[data-quest-status]');if(b)nextQuestStatus(b.dataset.questStatus)});$('#assetList').addEventListener('click',e=>{const b=e.target.closest('[data-delete-asset]');if(b){S.assets.splice(Number(b.dataset.deleteAsset),1);save();U.renderAll()}});
 document.addEventListener('click',e=>{const n=e.target.closest('[data-module]');if(n){$$('.world-node').forEach(x=>x.classList.remove('active'));n.classList.add('active');const card=$(`[data-module-card="${n.dataset.module}"]`);card?.scrollIntoView({behavior:'smooth',block:'center'});$('#worldBubble').textContent=card?.querySelector('p')?.textContent||'พร้อมทำงาน'}const f=e.target.closest('[data-focus]');if(f)document.getElementById(f.dataset.focus)?.focus()});
 $('#exportGdd').onclick=()=>download(`${slug(S.project.name)}-GDD.md`,F.markdown(),'text/markdown');$('#exportJson').onclick=()=>download(`${slug(S.project.name)}-project.json`,JSON.stringify(F.payload(),null,2),'application/json');$('#exportHtml').onclick=()=>download(`${slug(S.project.name)}-project.html`,F.html(),'text/html');$('#exportZip').onclick=exportZip;$('#saveDrive').onclick=saveDrive;$('#printReport').onclick=()=>window.print();$('#newProjectBtn').onclick=()=>{if(confirm('เริ่ม Project ใหม่และล้างข้อมูล Local ปัจจุบัน?')){localStorage.removeItem(F.STORAGE);location.reload()}};$('#editProjectBtn').onclick=()=>$('#projectName').focus();$('#bossStatus').onclick=createReceipt;
}
async function init(){U.renderAll();bind();const h=await api('health',()=>AGISSProcessor.health());$('#statusProcessor').textContent=h.ok?'ONLINE':'LOCAL MODE';if(h.ok)addChat('System','Processor พร้อมรับ Job และ Mission','system');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
init();
})();